apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
    name: build-image-taskrun
    namespace: tekton
spec:
    serviceAccountName: tutorial-service
    taskRef: 
        name: build-image
    resources:
      inputs:
          - name: pipeline-demo-project
            resourceRef: 
               name: git-hello1
      outputs:
          - name: builtImage
            resourceRef:
               name: image-hello1
    params:
        - name: pathToDockerfile
          value: deployment/Dockerfile
        - name: pathToContext
          value: /workspace/pipeline-demo-project
   