apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
    name: tutorial-pipeline
    namespace: tekton
spec:
    resources: 
        - name: source-repo
          type: git
        - name: web-image
          type: image
    task: 
